// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChipDirs() {
  return window['go']['main']['App']['GetChipDirs']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartScheduler() {
  return window['go']['main']['App']['StartScheduler']();
}

export function StartSync() {
  return window['go']['main']['App']['StartSync']();
}

export function StopScheduler() {
  return window['go']['main']['App']['StopScheduler']();
}
