// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetChipDirs():Promise<Array<string>>;

export function GetConfig():Promise<config.Config>;

export function GetLogs():Promise<Array<string>>;

export function GetSyncStatus():Promise<{[key: string]: any}>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectDirectory():Promise<string>;

export function StartScheduler():Promise<void>;

export function StartSync():Promise<void>;

export function StopScheduler():Promise<void>;
